name: DocFX CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install DocFX 2.78.3
        run: dotnet tool update -g docfx --version 2.78.3

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"

      - name: Build DocFX to _site
        run: docfx build docfx.json -o _site

      - name: Verify output
        run: test -f _site/index.html

      - name: Upload _site artifact
        uses: actions/upload-artifact@v4
        with:
          name: docfx-site
          path: _site
